@baseUrl = http://localhost:8080/odata/v4
@itemId = 784ce153-11e9-419e-bc49-1bab9e996a7c

### get all item configs
GET {{baseUrl}}/ItemService/ItemConfigs

### get item config by id
GET {{baseUrl}}/ItemService/ItemConfigs({{itemId}})

### create item config
POST {{baseUrl}}/ItemService/ItemConfigs
Content-Type: application/json

{
    "name": "Katamino Family",
    "description": "A good game for family",
    "price": 385000,
    "currency_code": "VND",
    "stock": 10
}